FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY ./services/room_manager/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./services/room_manager/ /app/room_manager

CMD ["uvicorn", "room_manager.main:app", "--host", "0.0.0.0", "--port", "8002", "--reload"]