FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY ./services/user_manager/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./services/user_manager/ /app/user_manager

CMD ["uvicorn", "user_manager.main:app", "--host", "0.0.0.0", "--port", "8003", "--reload"]