FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY ./services/booking_manager/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./services/booking_manager/ /app/booking_manager

CMD ["uvicorn", "booking_manager.main:app", "--host", "0.0.0.0", "--port", "8004", "--reload"]